export default {
  PERMISSION: {
    GET: 'permission get',
    UPDATE: 'permission update',
  },
  PERMISSION_CATEGORY: {
    GET: 'permission category get',
    UPDATE: 'permission category update',
  },
  ROLE: {
    GET: 'role get',
    CREATE: 'role create',
    DETAILS: 'role details',
    UPDATE: 'role update',
    DELETE: 'role delete',
    PERMISSION_ASSIGN: 'permissions assign in role',
  },
  USER: {
    GET: 'user get',
    CREATE: 'user create',
    DETAILS: 'user details',
    UPDATE: 'user update',
    DELETE: 'user delete',
    ROLE_ASSIGN: 'roles assign in user',
  },
  PRODUCT: {
    GET: 'Product get',
    CREATE: 'Product create',
    DETAILS: 'Product details',
    UPDATE: 'Product update',
    DELETE: 'Product delete',
  },
  PRODUCT_CATEGORY: {
    GET: 'Product category get',
    CREATE: 'Product category create',
    DETAILS: 'Product category details',
    UPDATE: 'Product category update',
    DELETE: 'Product category delete',
  },
  INVENTORY: {
    GET: 'Inventory get',
    CREATE: 'Inventory create',
    DETAILS: 'Inventory details',
    UPDATE: 'Inventory update',
    DELETE: 'Inventory delete',
  },
  UNIT: {
    GET: 'Unit get',
    CREATE: 'Unit create',
    DETAILS: 'Unit details',
    UPDATE: 'Unit update',
    DELETE: 'Unit delete',
  },
  SUPPLIER: {
    GET: 'Supplier get',
    CREATE: 'Supplier create',
    DETAILS: 'Supplier details',
    UPDATE: 'Supplier update',
    DELETE: 'Supplier delete',
  },
  BRAND: {
    GET: 'Brand get',
    CREATE: 'Brand create',
    DETAILS: 'Brand details',
    UPDATE: 'Brand update',
    DELETE: 'Brand delete',
  },
  SHOP: {
    GET: 'Shop get',
    CREATE: 'Shop create',
    DETAILS: 'Shop details',
    UPDATE: 'Shop update',
    DELETE: 'Shop delete',
  },
  PASSWROD_RESET: {
    UPDATE: 'Password reset',
  },
};
